const AREAS = ['Producción', 'NDT', 'Laboratorio', 'Ingeniería', 'G-CAD'];

const DEPARTAMENTOS = [
  'Ingeniería',
  'Laboratorio y NDT',
  'Nextgen factory',
  'Producción',
  'Prototipos',
  'Termoplásticos',
  'Termoestables',
];

const PROGRAMAS = [
  'Laboratorio y Calidad',
  'Programa aeronáuticos',
  'Programa Airbus comercial',
  'P. no aeronáuticos y P. financiados',
  'Programa no aeronáuticos',
  'Programa finanzas',
];

const AREA_ALIASES = {
  Produccion: 'Producción',
  'Producción': 'Producción',
  produccion: 'Producción',
  ' producción': 'Producción',
  NDT: 'NDT',
  ndt: 'NDT',
  Laboratorio: 'Laboratorio',
  laboratorio: 'Laboratorio',
  Ingenieria: 'Ingeniería',
  'Ingeniería': 'Ingeniería',
  ingenieria: 'Ingeniería',
  ingeneria: 'Ingeniería',
  ingeniería: 'Ingeniería',
  Gcad: 'G-CAD',
  'G-CAD': 'G-CAD',
  gcad: 'G-CAD',
  'g-cad': 'G-CAD',
};

const DEPARTAMENTO_ALIASES = {
  Ingenieria: 'Ingeniería',
  'Ingeniería': 'Ingeniería',
  ingenieria: 'Ingeniería',
  ingeniería: 'Ingeniería',
  ingeneria: 'Ingeniería',
  'Laboratorio y NDT': 'Laboratorio y NDT',
  'laboratorio y ndt': 'Laboratorio y NDT',
  'laboratorio ndt': 'Laboratorio y NDT',
  'Nextgen factory': 'Nextgen factory',
  'nextgen factory': 'Nextgen factory',
  'Nuevas tecnologias': 'Nextgen factory',
  'Nuevas tecnologías': 'Nextgen factory',
  'nuevas tecnologias': 'Nextgen factory',
  'nuevas tecnologías': 'Nextgen factory',
  Produccion: 'Producción',
  'Producción': 'Producción',
  produccion: 'Producción',
  Prototipos: 'Prototipos',
  prototipos: 'Prototipos',
  Termoestables: 'Termoestables',
  termoestables: 'Termoestables',
  Termoplasticos: 'Termoplásticos',
  'Termoplásticos': 'Termoplásticos',
  termoplasticos: 'Termoplásticos',
  termoplásticos: 'Termoplásticos',
};

const PROGRAMA_ALIASES = {
  'Laboratorio y Calidad': 'Laboratorio y Calidad',
  'laboratorio y calidad': 'Laboratorio y Calidad',
  'Programa aeronáuticos': 'Programa aeronáuticos',
  'Programa aeronauticos': 'Programa aeronáuticos',
  'programa aeronáuticos': 'Programa aeronáuticos',
  'programa aeronauticos': 'Programa aeronáuticos',
  'programas aeronáuticos': 'Programa aeronáuticos',
  'programas aeronauticos': 'Programa aeronáuticos',
  'Programa Airbus comercial': 'Programa Airbus comercial',
  'programa airbus comercial': 'Programa Airbus comercial',
  'programas airbus comercial': 'Programa Airbus comercial',
  'P. no aeronáuticos y P. financiados': 'P. no aeronáuticos y P. financiados',
  'P. no aeronauticos y P. financiados': 'P. no aeronáuticos y P. financiados',
  'p. no aeronáuticos y p. financiados': 'P. no aeronáuticos y P. financiados',
  'p. no aeronauticos y p. financiados': 'P. no aeronáuticos y P. financiados',
  'P. no aeronáutiocos y P. financiados': 'P. no aeronáuticos y P. financiados',
  'p. no aeronáutiocos y p. financiados': 'P. no aeronáuticos y P. financiados',
  'Programa no aeronáuticos': 'Programa no aeronáuticos',
  'Programa no aeronauticos': 'Programa no aeronáuticos',
  'programa no aeronáuticos': 'Programa no aeronáuticos',
  'programa no aeronauticos': 'Programa no aeronáuticos',
  'Programa finanzas': 'Programa finanzas',
  'programa finanzas': 'Programa finanzas',
  'P. financiados': 'Programa finanzas',
  'p. financiados': 'Programa finanzas',
};

const DEFAULT_CATEGORIAS = {
  'G-CAD': [
    'Fallo programa máquina',
    'Diseño utillaje',
    'Incidencia cliente externo',
    'Falta CoD',
    'Fallo de planificación',
  ],
  NDT: [
    'Entrega del panel sin la IT',
    'ID errónea del elemento',
    'Especificación incorrecta del elemento',
    'Fallo equipos/parada máquina',
    'Incumplimiento planificación por parte de NDT y/o cliente',
    'No hay línea de NDT en la hoja de proceso',
    'La pieza se envía al cliente/lab sin inspeccionar',
    'Otros',
    'Reporte resultados incompleto/incorrecto',
    'IDINET: gestión de Proyectos',
    'IDINET: planificación no actualizada',
    'Incidencia cliente externo',
    'Falta de formación o destreza',
    'No se realiza inspección visual',
    'Fallo de planificación',
  ],
  'Ingeniería': [
    'Pérdida trazabilidad espécimen',
    'Aprovisionamiento materiales/Utillaje',
    'Diseño utillaje',
    'Reporte resultados incompleto/incorrecto',
    'Incorrecta definición en el proceso',
    'Incorrecta definición de ciclo de autoclave',
    'Falta proceso',
    'Incumplimiento del procedimiento',
    'IDINET: Gestión de Proyectos',
    'IDINET. planificación no actualizada',
    'Falta soporte ingeniería',
    'Falta programa máquina',
    'Incidencia cliente externo',
    'PE mal definida',
    'Falta CoD',
    'Falta CoC',
    'Fallo de planificación',
  ],
  Laboratorio: [
    'Selección de los parámetros de ensayo incorrectas',
    'Fallo en el corte de las probetas',
    'Realización incorrecta del ensayo',
    'Petición mal ejecutada por el técnico',
    'Fallo operario pegado de tacones',
    'Mantenimiento de equipos',
    'No se realiza inspección visual',
    'Fallo equipos/parada máquina',
    'Fallo análisis dimensional',
    'Incorrecto montaje del set-up de ensayos',
    'Útil dañado',
    'Informe de resultados incorrecto',
    'Fallo uso de la marca ENAC y NADCAP',
    'Pérdida trazabilidad espécimen',
    'IDINET: Gestión de Proyectos',
    'IDINET: planificación no actualizada',
    'Incidencia cliente externo',
    'Falta de formación o destreza',
    'Fallo de planificación',
  ],
  'Producción': [
    'Incumplimiento del procedimiento',
    'Incidencia en ciclo de curado',
    'Fallo máquina',
    'Operación mal ejecuta por operario',
    'Aprovisionamiento materiales/Utillaje',
    'Fallo de planificación',
    'Incidencia cliente externo',
    'Falta de formación o destreza',
    'Error diseño de utillaje',
    'Sin clasificación',
    'Pérdida trazabilidad espécimen',
  ],
};

module.exports = {
  AREAS,
  DEPARTAMENTOS,
  PROGRAMAS,
  AREA_ALIASES,
  DEPARTAMENTO_ALIASES,
  PROGRAMA_ALIASES,
  DEFAULT_CATEGORIAS,
};
